### ISSUE TITLE
Have you thought about scraping other op-eds?

### ISSUE THREAD

**Issue by smasongarrison** [mkearney/resist_oped#1]
I think that using tweet data is great. But I'd suggest comparing the anon oped to other op-eds. It should eliminate some method bias.

**Comment by smasongarrison** [comment]
There's probably a better way to scrape writings from high level officials. Maybe crowdsource it?

Mike Pence:
http://web.archive.org/web/20010415085348/http://mikepence.com/smoke.html

**Comment by mkearney** [comment]
Agreed. Ideally, someone else would give this project the attention it deserves lol.
