### ISSUE TITLE
Adding the id column from data onto tf

### ISSUE THREAD

**Issue by cdibble** [mkearney/resist_oped#2]
I think you need to add a line as follows:

`tf$id <- data$id`

prior to doing the summary

`tfsum <- tf %>%
    group_by(id) %>%
    summarise_all(mean, na.rm = TRUE) %>%
    ungroup()`

FYI I took your data tfsum and ran a quick non-metric multidimensional scaling analysis and got this:

![image](https://user-images.githubusercontent.com/8380659/45135090-74370e80-b152-11e8-8d58-6a8c3e9b8f2a.png)

Somewhat agrees with your correlation analysis, though puts POTUS and VP out of the running, which makes sense. Happy to share the code if you're interested.

**Comment by mkearney** [comment]
I fairly certain this is a function of the GH version of [textfeatures](https://textfeatures.mikewk.com) being ahead of the CRAN version. I'll hopefully submit textfeatures update to CRAN soon!

**Comment by cdibble** [comment]
Yeah I thought that might be the case since the textfeatures arguments you used were not understood by the version I got from CRAN. Cool package, though. I like it. 

Any interest in the NMDS? I get Nielsen, Carson, Devos as the top picks by that analysis.
