### ISSUE TITLE
Soooooo, who is it?

### ISSUE THREAD

**Issue by cooganb** [mkearney/resist_oped#4]

**Comment by GregHilston** [comment]
@cooganb Can't you read the graph and make your own decisions? I don't mean to be rude, but this is just an analysis on a handful of selected people. 

The real author very well may not be in even in the scope of selected individuals.

**Comment by cooganb** [comment]
Oh! Missed that. 

Still having trouble reading the graph, but best of my ability: Top bids Pence, Trump himself (nice), Wilbur Ross (Commerce) Mike Pompeo (State, formerly CIA), Kirstjen Nielsen (Homeland Security)

Correlation DOES equal causation!

**Comment by GregHilston** [comment]
> Correlation DOES equal causation!

I think many people would disagree with this statement.

Basically, what I'm trying to say is there's not going to be a definitive answer with this type of analysis. There can be a very strong suggested answer, but not definitive. You'll have to decide for yourself what is convincing and what isn't.

**Comment by GregHilston** [comment]
Additionally, I suggest closing your issue.

**Comment by Artoria2e5** [comment]
Since a bunch of word2vec features are used, it's possible that the similarities found are related to the topics -- instead of say, style -- of these posters. For example, one thing the VP and POTUS accounts talk a lot about would definitely be "President/Mr. Trump", which also has 8 occurences in the op-ed.

**Comment by mkearney** [comment]
good points @Artoria2e5 ! 

This isn't meant to be definitive proof (or even any level of proof) of anything. The approach might have some potential, but you'd need more and better data before the estimates could be taken seriously.

**Comment by mkearney** [comment]
closing this b/c i'm working on publishing explanation with list of limitations
