### ISSUE TITLE
What is the starting point of your project?

### ISSUE THREAD

**Issue by pranayaryal** [mkearney/resist_oped#6]
What is the starting point of your project? thanks. Great work. But didn't see this information in the readme file.

**Comment by mkearney** [comment]
This is a good question. In theory, you would start with [R/data-twitter.R](R/data-twitter.R) and then move to [R/plot.R](R/plot.R) to replicate visualization. I should probably pick a better name than `data-twitter.R`.

I've been meaning to add some session information with software/version information. I used the dev version of [textfeatures](https://textfeatures.mikewk.com), for example. When I do that (probably sometime this weekend), I'll also add some replication instructions to the readme file!

**Comment by mkearney** [comment]
Added some package installation/version checks and add starting point indication to README. See: 6acbffec
